=== iconmaster5326/YGOJSON/schema/v1/card.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/iconmaster5326/YGOJSON/main/schema/v1/card.json",
  "title": "Card",
  "description": "A logical Yu-Gi-Oh card (as opposed to a physical card, of which belongs to a set).",
  "type": "object",
  "required": [
    "$schema",
    "id",
    "text",
    "cardType",
    "passwords",
    "images",
    "sets",
    "legality",
    "externalIDs",
    "series"
  ],
  "properties": {
    "$schema": {
      "const": "https://raw.githubusercontent.com/iconmaster5326/YGOJSON/main/schema/v1/card.json"
    },
    "id": {
      "description": "The UUID of this card. The name of the card's file should be this UUID.",
      "type": "string",
      "format": "uuid"
    },
    "text": {
      "description": "A map of locales to textual card information.",
      "type": "object",
      "additionalProperties": {
        "description": "Textual information on the card.",
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "description": "The name of the card.",
            "type": "string"
          },
          "effect": {
            "description": "All text in the main text box of the card. (Normal monster flavor also goes here, despite the name.) Null if the card's text is unknown or untranslated.",
            "type": "string"
          },
          "pendulumEffect": {
            "description": "All text in the pendulum text box of the card. Only appears on pendulum cards.",
            "type": "string"
          },
          "official": {
            "description": "Is this translation official or not? Default is true.",
            "type": "boolean"
          }
        }
      }
    },
    "cardType": {
      "description": "The broadest category of card (monster, spell, trap, etc.)",
      "enum": [
        "monster",
        "spell",
        "trap",
        "token",
        "skill"
      ]
    },
    "attribute": {
      "description": "The monster attribute. Only appears on monster or token cards.",
      "enum": [
        "light",
        "dark",
        "fire",
        "water",
        "wind",
        "earth",
        "divine"
      ]
    },
    "monsterCardTypes": {
      "description": "What summoning types this card is, if any. Only appears on monster cards.",
      "type": "array",
      "items": {
        "enum": [
          "ritual",
          "fusion",
          "synchro",
          "xyz",
          "pendulum",
          "link"
        ]
      }
    },
    "type": {
      "description": "The race of monster. Only appears on monster or token cards.",
      "enum": [
        "beastwarrior",
        "zombie",
        "fiend",
        "dinosaur",
        "dragon",
        "beast",
        "illusion",
        "insect",
        "wingedbeast",
        "warrior",
        "seaserpent",
        "aqua",
        "pyro",
        "thunder",
        "spellcaster",
        "plant",
        "rock",
        "reptile",
        "fairy",
        "fish",
        "machine",
        "divinebeast",
        "psychic",
        "creatorgod",
        "wyrm",
        "cyberse"
      ]
    },
    "classifications": {
      "description": "Any non-type, non-ability categories appearing on the type line (effect, normal, etc). Only appears on monster or token cards.",
      "type": "array",
      "items": {
        "enum": [
          "normal",
          "effect",
          "pendulum",
          "tuner",
          "specialsummon"
        ]
      }
    },
    "abilities": {
      "description": "Any non-type, ability categories appearing on the type line (toon, spirit, etc). Only appears on monster or token cards.",
      "type": "array",
      "items": {
        "enum": [
          "toon",
          "spirit",
          "union",
          "gemini",
          "flip"
        ]
      }
    },
    "level": {
      "description": "The level of this card. Only appears on non-link, non-xyz monster or token cards.",
      "type": "integer"
    },
    "rank": {
      "description": "The rank of this card. Only appears on xyz monster cards.",
      "type": "integer"
    },
    "atk": {
      "description": "The ATK of the card. Either a number, or '?'. Only appears on monster or token cards.",
      "oneOf": [
        {
          "type": "integer"
        },
        {
          "const": "?"
        }
      ]
    },
    "def": {
      "description": "The DEF of the card. Either a number, or '?'. Only appears on non-link monster cards.",
      "oneOf": [
        {
          "type": "integer"
        },
        {
          "const": "?"
        }
      ]
    },
    "scale": {
      "description": "The pendulum scale. Only appears on pendulum monster cards.",
      "type": "integer"
    },
    "linkArrows": {
      "description": "The link arrows on this card. Only appears on link monster cards.",
      "type": "array",
      "items": {
        "enum": [
          "topleft",
          "topcenter",
          "topright",
          "middleleft",
          "middleright",
          "bottomleft",
          "bottomcenter",
          "bottomright"
        ]
      }
    },
    "subcategory": {
      "description": "The type of spell/trap card this is. Only appears on spell/trap cards.",
      "enum": [
        "normal",
        "continuous",
        "equip",
        "quickplay",
        "field",
        "ritual",
        "counter"
      ]
    },
    "character": {
      "description": "The character a skill card corresponds to. Only present in skill cards.",
      "type": "string"
    },
    "skillType": {
      "description": "The card type a skill card is. Only present in skill cards.",
      "type": "string"
    },
    "passwords": {
      "description": "All official passwords given for the card.",
      "type": "array",
      "items": {
        "description": "A password, as printed on the card.",
        "type": "string",
        "regex": "\\d\\d\\d\\d\\d\\d\\d\\d"
      }
    },
    "images": {
      "description": "Card images, one per art variant. These images are generic to the card, generated automatically and in English, rather than being the image of a specific printing.",
      "type": "array",
      "items": {
        "description": "An image for a specific art treatment of a card.",
        "type": "object",
        "required": [
          "id"
        ],
        "properties": {
          "id": {
            "description": "The UUID of this art treatment. Used to refer to specific art treatments from specific printings.",
            "type": "string",
            "format": "uuid"
          },
          "password": {
            "description": "The password this art is given to. Some cards have multiple passwords, one per art. Some cards have multiple arts with the same password. And some have both going on. Not present if the card's password is currently unknown, or the card has no passwords, such as is the case for tokens.",
            "type": "string",
            "regex": "\\d\\d\\d\\d\\d\\d\\d\\d"
          },
          "art": {
            "description": "An art crop of this card.",
            "type": "string",
            "format": "uri"
          },
          "card": {
            "description": "An image of this card.",
            "type": "string",
            "format": "uri"
          }
        }
      }
    },
    "sets": {
      "description": "A list of sets each card was (or will be) found in. Look up these UUIDs in the set JSON for printing information.",
      "type": "array",
      "items": {
        "description": "A UUID of the set this card appears in.",
        "type": "string",
        "format": "uuid"
      }
    },
    "illegal": {
      "description": "If true, then this card is illegal, and will not have any legality history. Never set for cards that are not game pieces, such as tokens.",
      "type": "boolean"
    },
    "legality": {
      "description": "A mapping of formats to legalities.",
      "type": "object",
      "additionalProperties": {
        "description": "Legality information for this format. Never set for cards that are illegal or are not game pieces (such as tokens).",
        "type": "object",
        "required": [
          "current"
        ],
        "properties": {
          "current": {
            "description": "The current legality of this card. Use this to avoid reading the legality history, or use this when the legality history is unknown/empty.",
            "enum": [
              "unlimited",
              "semilimited",
              "limited",
              "forbidden",
              "limit1",
              "limit2",
              "limit3",
              "unreleased"
            ]
          },
          "history": {
            "description": "The legality history for this card. Only present if this history is known, but may be empty even if known, in the case of cards whose legality has never changed.",
            "type": "array",
            "items": {
              "description": "A record of a change in legality.",
              "type": "object",
              "required": [
                "legality",
                "date"
              ],
              "properties": {
                "legality": {
                  "description": "What the legality was changed to.",
                  "enum": [
                    "unlimited",
                    "semilimited",
                    "limited",
                    "forbidden",
                    "limit1",
                    "limit2",
                    "limit3"
                  ]
                },
                "date": {
                  "description": "The date of the change.",
                  "type": "string",
                  "format": "date"
                }
              }
            }
          }
        }
      }
    },
    "masterDuel": {
      "description": "Any Master Duel specific information. Only present if this card is in Master Duel.",
      "type": "object",
      "required": [
        "rarity",
        "craftable"
      ],
      "properties": {
        "rarity": {
          "description": "The rairty of this card.",
          "enum": [
            "n",
            "r",
            "sr",
            "ur"
          ]
        },
        "craftable": {
          "description": "Is this card craftable using dust?",
          "type": "boolean"
        }
      }
    },
    "duelLinks": {
      "description": "Any Duel Links specific information. Only present if this card is in Duel Links.",
      "type": "object",
      "required": [
        "rarity"
      ],
      "properties": {
        "rarity": {
          "description": "The rairty of this card.",
          "enum": [
            "n",
            "r",
            "sr",
            "ur"
          ]
        }
      }
    },
    "externalIDs": {
      "description": "IDs and other information, to access this card from various other sites.",
      "type": "object",
      "required": [],
      "properties": {
        "yugipedia": {
          "description": "Information for Yugipedia. This array is usually 1 element long, but some cards, like Polymerizarion or the God Cards, have multiple Yugipedia pages that represent the same card.",
          "type": "array",
          "items": {
            "description": "A Yugipedia page.",
            "type": "object",
            "required": [
              "id",
              "name"
            ],
            "properties": {
              "name": {
                "description": "The page name for this card.",
                "type": "string"
              },
              "id": {
                "description": "The internal wiki ID for the page for this card.",
                "type": "integer"
              }
            }
          }
        },
        "dbID": {
          "description": "The CID this card has on db.yugioh-card.com.",
          "type": "integer"
        },
        "ygoprodeck": {
          "description": "Information for YGOProDeck, if available",
          "type": "object",
          "required": [
            "id",
            "name"
          ],
          "properties": {
            "name": {
              "description": "The slug for YGOProDeck you can use after 'ygoprodeck.com/card/' to get the card's page.",
              "type": "string"
            },
            "id": {
              "description": "The internal ID in YGOProDeck for this card. Usually the password of the card, but may be an invented password, in the case of passwordless cards.",
              "type": "integer"
            }
          }
        },
        "yugiohpricesName": {
          "description": "The slug for YugiohPrices and YugiohTopDecks you can use to get the card's page.",
          "type": "string"
        },
        "yamlyugiID": {
          "description": "The internal ID in YamlYugi for this card. Usually the password of the card, but may be an invented password, in the case of passwordless cards.",
          "type": "integer"
        }
      }
    },
    "errata": {
      "description": "Present only if this card has recieved errata. Details how the card has changed over time. Does not cover format legality information.",
      "type": "object",
      "required": [
        "original",
        "history"
      ],
      "properties": {
        "original": {
          "description": "What is the original state of the card, as first printed? A subset of the card json, with only changed properties present.",
          "type": "object"
        },
        "history": {
          "description": "The change history.",
          "type": "array",
          "items": {
            "description": "A change.",
            "type": "object",
            "required": [
              "date",
              "changes",
              "official"
            ],
            "properties": {
              "date": {
                "description": "The date of the change.",
                "type": "string",
                "format": "date"
              },
              "changes": {
                "description": "What changed with this errata. A subset of the card json, with only changed properties present.",
                "type": "object"
              },
              "official": {
                "description": "Was this change official? Unofficial changes may occur in the case of a temporary name/text beging updated when a card officially comes out in that locale.",
                "type": "boolean"
              }
            }
          }
        }
      }
    },
    "series": {
      "description": "Any series or archetypes this card is a part of.",
      "type": "array",
      "items": {
        "description": "The UUID of the series. Look it up in the series JSON.",
        "type": "string",
        "format": "uuid"
      }
    }
  }
}

=== iconmaster5326/YGOJSON/cards/507afda0-de1e-4d93-a931-3de7994482b0.json
{
  "$schema": "https://raw.githubusercontent.com/iconmaster5326/YGOJSON/main/schema/v1/card.json",
  "id": "507afda0-de1e-4d93-a931-3de7994482b0",
  "text": {
    "en": {
      "name": "Warm Worm",
      "official": false
    },
    "de": {
      "name": "Warmer Wurm",
      "effect": "Falls diese Karte zerst\u00f6rt wird, lege die obersten 3 Karten vom Deck deines Gegners auf den Friedhof."
    },
    "es": {
      "name": "Gusano Ardiente",
      "effect": "Si esta carta es destruida, manda al Cementerio a las 3 cartas de la parte superior del Deck de tu adversario."
    },
    "fr": {
      "name": "Ver de Feu",
      "effect": "Si cette carte est d\u00e9truite, envoyez les 3 cartes du dessus du Deck de votre adversaire au Cimeti\u00e8re."
    },
    "it": {
      "name": "Verme Ardente",
      "effect": "Se questa carta viene distrutta, manda 3 carte del Deck del tuo avversario al Cimitero."
    },
    "pt": {
      "name": "Lombriga Ardente",
      "effect": "Se este card for destru\u00eddo, envie os 3 cards do topo do Deck do oponente para o Cemit\u00e9rio."
    },
    "ja": {
      "name": "\u30a6\u30a9\u30fc\u30e0\u30fb\u30ef\u30fc\u30e0",
      "effect": "\u2460\uff1a\u3053\u306e\u30ab\u30fc\u30c9\u304c\u7834\u58ca\u3055\u308c\u305f\u5834\u5408\u306b\u767a\u52d5\u3059\u308b\u3002\u76f8\u624b\u306e\u30c7\u30c3\u30ad\u306e\u4e0a\u304b\u3089\u30ab\u30fc\u30c9\u3092\uff13\u679a\u5893\u5730\u3078\u9001\u308b\u3002"
    },
    "ko": {
      "name": "\uc6b0\uc634 \uc6dc",
      "effect": "\uc774 \uce74\ub4dc\uac00 \ud30c\uad34\ub418\uc5c8\uc744 \uacbd\uc6b0, \uc0c1\ub300\uc758 \ub371 \uc704\uc5d0\uc11c \uce74\ub4dc\ub97c 3\uc7a5 \ubb18\uc9c0\ub85c \ubcf4\ub0b8\ub2e4."
    },
    "zh-TW": {
      "name": "\u6696\u7570\u87f2",
      "effect": "\u2460\uff1a\u5728\u6b64\u5361\u88ab\u7834\u58de\u7684\u72c0\u6cc1\u4e0b\u767c\u52d5\u3002\u5f9e\u5c0d\u65b9\u724c\u7d44\u4e0a\u65b9\u5c07\uff13\u5f35\u5361\u9001\u81f3\u5893\u5730\u3002"
    },
    "zh-CN": {
      "name": "\u6696\u866b",
      "effect": "\u2460\uff1a\u8fd9\u5f20\u5361\u88ab\u7834\u574f\u7684\u573a\u5408\u53d1\u52a8\u3002\u4ece\u5bf9\u65b9\u5361\u7ec4\u4e0a\u9762\u628a3\u5f20\u5361\u9001\u53bb\u5893\u5730\u3002"
    }
  },
  "cardType": "monster",
  "attribute": "fire",
  "type": "insect",
  "classifications": [
    "effect"
  ],
  "level": 3,
  "atk": 600,
  "def": 1400,
  "passwords": [
    "16751086"
  ],
  "images": [
    {
      "id": "3328e945-165f-409e-b0c7-ec480c01675f",
      "password": "16751086",
      "art": "https://images.ygoprodeck.com/images/cards_cropped/16751086.jpg",
      "card": "https://images.ygoprodeck.com/images/cards/16751086.jpg"
    }
  ],
  "sets": [
    "bbda8e12-e5c7-4746-9779-9d3b45c5f274",
    "bbda8e12-e5c7-4746-9779-9d3b45c5f274",
    "bbda8e12-e5c7-4746-9779-9d3b45c5f274",
    "bbda8e12-e5c7-4746-9779-9d3b45c5f274",
    "bbda8e12-e5c7-4746-9779-9d3b45c5f274",
    "bbda8e12-e5c7-4746-9779-9d3b45c5f274",
    "bbda8e12-e5c7-4746-9779-9d3b45c5f274",
    "eee52c01-808d-4796-bb87-f18c2d134843",
    "1834d6ae-ba04-4cb4-b15a-cd08c8f8aacb",
    "744d6edc-439a-4817-955b-3df1fa1a7ecf"
  ],
  "legality": {
    "tcg": {
      "current": "unlimited"
    },
    "ocg": {
      "current": "unlimited"
    }
  },
  "masterDuel": {
    "rarity": "r",
    "craftable": true
  },
  "duelLinks": {
    "rarity": "sr"
  },
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Warm Worm",
        "id": 48242
      }
    ],
    "dbID": 8517,
    "ygoprodeck": {
      "id": 16751086,
      "name": "warm-worm-1441"
    },
    "yamlyugiID": 16751086
  },
  "series": [
    "6184491c-679a-4951-bb46-52bde1714507"
  ]
}

=== iconmaster5326/YGOJSON/cards/991b6004-d82d-4d40-9960-720bec05dff1.json
{
  "$schema": "https://raw.githubusercontent.com/iconmaster5326/YGOJSON/main/schema/v1/card.json",
  "id": "991b6004-d82d-4d40-9960-720bec05dff1",
  "text": {
    "en": {
      "name": "Dealer's Choice",
      "official": false
    },
    "de": {
      "name": "Wahl des Gebers",
      "effect": "Jeder Spieler mischt sein Deck, dann zieht jeder Spieler 1 Karte, dann wirft jeder Spieler 1 Karte ab."
    },
    "es": {
      "name": "Elecci\u00f3n del Repartidor",
      "effect": "Cada jugador baraja su Deck, y despu\u00e9s cada jugador roba 1 carta, y despu\u00e9s cada jugador descarta 1 carta."
    },
    "fr": {
      "name": "Choix du Donneur",
      "effect": "Chaque joueur m\u00e9lange son Deck, puis chaque joueur pioche 1 carte, puis chaque joueur d\u00e9fausse 1 carte."
    },
    "it": {
      "name": "Scelta del Banco",
      "effect": "Ogni giocatore mischia il suo Deck, poi ogni giocatore pesca 1 carta, poi ogni giocatore scarta 1 carta."
    },
    "pt": {
      "name": "Escolha do Carteador",
      "effect": "Cada duelista embaralha seu Deck e, depois, cada duelista compra 1 card e, depois, cada duelista descarta 1 card."
    },
    "ja": {
      "name": "\u30c7\u30a3\u30fc\u30e9\u30fc\u30ba\u30fb\u30c1\u30e7\u30a4\u30b9",
      "effect": "\u2460\uff1a\u304a\u4e92\u3044\u306e\u30d7\u30ec\u30a4\u30e4\u30fc\u306f\u3001\u30c7\u30c3\u30ad\u3092\u30b7\u30e3\u30c3\u30d5\u30eb\u3057\u3001\u30c7\u30c3\u30ad\u304b\u3089\uff11\u679a\u30c9\u30ed\u30fc\u3059\u308b\u3002\u305d\u306e\u5f8c\u3001\u304a\u4e92\u3044\u306e\u30d7\u30ec\u30a4\u30e4\u30fc\u306f\u624b\u672d\u3092\uff11\u679a\u9078\u3093\u3067\u6368\u3066\u308b\u3002"
    },
    "ko": {
      "name": "\ub51c\ub7ec\uc988 \ucd08\uc774\uc2a4",
      "effect": "\u2460: \uc591\ucabd \ud50c\ub808\uc774\uc5b4\ub294, \ub371\uc744 \uc154\ud50c\ud558\uace0, \ub371\uc5d0\uc11c 1\uc7a5 \ub4dc\ub85c\uc6b0\ud55c\ub2e4. \uadf8 \ud6c4, \uc591\ucabd \ud50c\ub808\uc774\uc5b4\ub294 \ud328\ub97c 1\uc7a5 \uace0\ub974\uace0 \ubc84\ub9b0\ub2e4."
    },
    "zh-TW": {
      "name": "\u838a\u5bb6\u9078\u64c7",
      "effect": "\u2460\uff1a\u96d9\u65b9\u73a9\u5bb6\u5c07\u724c\u7d44\u6d17\u724c\uff0c\u5f9e\u724c\u7d44\u62bd\uff11\u5f35\u724c\u3002\u5176\u5f8c\uff0c\u96d9\u65b9\u73a9\u5bb6\u9078\u64c7\uff11\u5f35\u624b\u724c\u6368\u68c4\u3002"
    },
    "zh-CN": {
      "name": "\u5e84\u5bb6\u9009\u62e9",
      "effect": "\u2460\uff1a\u53cc\u65b9\u73a9\u5bb6\u628a\u5361\u7ec4\u6d17\u5207\uff0c\u4ece\u5361\u7ec4\u62bd1\u5f20\u3002\u90a3\u4e4b\u540e\uff0c\u53cc\u65b9\u73a9\u5bb6\u90091\u5f20\u624b\u5361\u4e22\u5f03\u3002"
    }
  },
  "cardType": "trap",
  "subcategory": "normal",
  "passwords": [
    "89462956"
  ],
  "images": [
    {
      "id": "d4b551bc-0305-4dd9-9f93-a7fdf7861ded",
      "password": "89462956",
      "art": "https://images.ygoprodeck.com/images/cards_cropped/89462956.jpg",
      "card": "https://images.ygoprodeck.com/images/cards/89462956.jpg"
    }
  ],
  "sets": [
    "d835a743-3c32-4ef7-98fa-2f70967b5bdc",
    "d835a743-3c32-4ef7-98fa-2f70967b5bdc",
    "d835a743-3c32-4ef7-98fa-2f70967b5bdc",
    "d835a743-3c32-4ef7-98fa-2f70967b5bdc",
    "d835a743-3c32-4ef7-98fa-2f70967b5bdc",
    "d835a743-3c32-4ef7-98fa-2f70967b5bdc",
    "d835a743-3c32-4ef7-98fa-2f70967b5bdc",
    "d835a743-3c32-4ef7-98fa-2f70967b5bdc",
    "dc2d9920-87cd-4afd-adf8-65bc91d1057c",
    "dc2d9920-87cd-4afd-adf8-65bc91d1057c",
    "dc2d9920-87cd-4afd-adf8-65bc91d1057c",
    "dc2d9920-87cd-4afd-adf8-65bc91d1057c",
    "dc2d9920-87cd-4afd-adf8-65bc91d1057c",
    "dc2d9920-87cd-4afd-adf8-65bc91d1057c"
  ],
  "legality": {
    "tcg": {
      "current": "unlimited"
    },
    "ocg": {
      "current": "unlimited"
    }
  },
  "masterDuel": {
    "rarity": "n",
    "craftable": true
  },
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Dealer's Choice",
        "id": 557472
      }
    ],
    "dbID": 13796,
    "ygoprodeck": {
      "id": 89462956,
      "name": "dealer-s-choice-9471"
    },
    "yamlyugiID": 89462956
  },
  "series": []
}
